#!/usr/bin/env python3
"""
Generate the landing page with the full Batman report embedded as static HTML.
"""
import json

from demo_batman import SIMULATED_REPORT

report = SIMULATED_REPORT

def esc(text):
    return (text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                .replace('"', "&quot;").replace("'", "&#39;"))

def fmt(text):
    """Format citations and basic markdown."""
    import re
    text = esc(text)
    text = re.sub(r'\[Source: ([^\]]+)\]', r'<span class="citation">[\1]</span>', text)
    return text

def build_section_html(s):
    html = f'<div class="report-section" id="{s["heading"].replace(chr(32),"-")[:60]}">'
    html += f'<h2>{esc(s["heading"])}</h2>'
    html += f'<p>{fmt(s["content"])}</p>'

    if s.get("table"):
        t = s["table"]
        html += '<div class="report-table-wrap"><table class="report-table">'
        html += '<thead><tr>' + ''.join(f'<th>{esc(h)}</th>' for h in t["headers"]) + '</tr></thead>'
        html += '<tbody>' + ''.join(
            '<tr>' + ''.join(f'<td>{esc(str(c))}</td>' for c in row) + '</tr>'
            for row in t["rows"]
        ) + '</tbody></table></div>'

    for sub in s.get("subsections", []):
        html += f'<h3>{esc(sub.get("heading",""))}</h3>'
        html += f'<p>{fmt(sub.get("content",""))}</p>'

    html += '</div>'
    return html


# Read existing landing page
with open("index.html", "r", encoding="utf-8") as f:
    landing = f.read()

# Find the demo box section and replace with full report
old_demo = '''  <!-- Demo -->
  <div class="section">
    <div class="demo-box">
      <h3 style="margin-top:0;">Try It: "Which actor is the greatest Batman?"</h3>
      <p style="color:var(--text2);font-size:14px;margin:8px 0 16px;">
        Pre-loaded demo session showing the full research output: 6 sections, 10 cited sources,
        6 key takeaways, data tables, and uncertainty notes. No API key needed to view.
      </p>
      <strong style="font-size:20px;">🦇 Who Is the Greatest Batman Actor? A Multi-Dimensional Analysis</strong>
      <p style="margin:8px 0;font-size:14px;">After analyzing critical reception, box office performance, cultural impact, and acting craft across 8 Batman actors from 1943–2026, <strong>Christian Bale</strong> leads in critical consensus and box office, while <strong>Kevin Conroy</strong> dominates as the definitive voice. However, "greatest" depends on criteria: Bale for realism, Keaton for trailblazing, Conroy for fidelity to source material, and Pattinson for psychological complexity.</p>

      <table class="compare-table">
        <tr><th>Actor</th><th>RT Avg</th><th>Box Office</th><th>Legacy</th></tr>
        <tr><td>Christian Bale</td><td>92%</td><td>$2.46B</td><td>Elevated superhero films to prestige cinema</td></tr>
        <tr><td>Kevin Conroy</td><td>95% (fans)</td><td>N/A</td><td>Definitive voice across 30 years</td></tr>
        <tr><td>Michael Keaton</td><td>78%</td><td>$1.19B</td><td>Proved dark Batman could succeed</td></tr>
        <tr><td>Robert Pattinson</td><td>85%</td><td>$0.77B</td><td>Most psychologically complex portrayal</td></tr>
      </table>

      <p style="font-size:13px;color:var(--text2);">Key takeaway: <em>"The 'greatest' question has no objective answer — it reveals more about what we value in the character than about the actors themselves."</em></p>
      <p style="font-size:12px;color:var(--text2);">Sources: Wikipedia, Rotten Tomatoes, IMDb, IGN, Variety, The Hollywood Reporter, RogerEbert.com</p>
    </div>
  </div>'''

# Build full report HTML
report_html = '''  <!-- ============================================================ -->
  <!-- FULL RESEARCH REPORT: Batman — Greatest Actor Analysis     -->
  <!-- ============================================================ -->
  <div class="section">
    <div class="demo-box" style="margin-bottom:32px;">
      <p style="color:var(--text2);font-size:13px;margin:0;">🦇 This is a static rendering of an actual DeepResearch output — 8 sections, 28 subsections, 4 data tables, 20 cited sources. Generated by the 4-agent pipeline: Planner → Searcher → Analyst → Synthesizer across 3 iterations.</p>
    </div>

    <div class="report-container active">
      <div class="report-header">
        <h1 class="report-title">''' + esc(report["title"]) + '''</h1>
        <div class="report-meta">Generated by DeepResearch · ''' + str(report["research_metadata"]["iterations"]) + ''' iterations · ''' + str(report["research_metadata"]["total_findings"]) + ''' findings · ''' + str(report["research_metadata"]["sub_questions_asked"]) + ''' sub-questions</div>
      </div>

      <div class="exec-summary">
        <strong style="color:var(--accent);">Executive Summary</strong><br><br>
        ''' + fmt(report["executive_summary"]) + '''
      </div>

      <!-- Table of Contents -->
      <div class="toc" style="background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);padding:16px 20px;margin-bottom:24px;">
        <strong style="color:var(--accent);font-size:14px;">📑 Table of Contents</strong>
        <ol style="margin:8px 0 0 18px;font-size:14px;line-height:1.8;">'''

for s in report["sections"]:
    anchor = s["heading"].replace(" ", "-")[:60]
    report_html += f'<li><a href="#{anchor}" style="color:var(--accent);text-decoration:none;">{esc(s["heading"])}</a></li>'

report_html += '''</ol></div>\n'''

# Sections
for s in report["sections"]:
    report_html += build_section_html(s)

# Key takeaways
report_html += '<h2 style="color:var(--accent2);">Key Takeaways</h2>'
report_html += '<ul class="takeaway-list">'
for t in report.get("key_takeaways", []):
    report_html += f'<li>{fmt(t)}</li>'
report_html += '</ul>'

# Uncertainty
if report.get("uncertainty_notes"):
    report_html += '<div class="uncertainty-box"><h3>⚠ Areas of Uncertainty</h3><ul>'
    for u in report["uncertainty_notes"]:
        report_html += f'<li>{esc(u)}</li>'
    report_html += '</ul></div>'

# Sources
report_html += '<h2>Sources</h2><ol class="source-list">'
for i, s in enumerate(report.get("sources", []), 1):
    url = s.get("url", "#")
    title = s.get("title", "Source")
    report_html += f'<li><a href="{esc(url)}" target="_blank" rel="noopener">{esc(title)}</a></li>'
report_html += '</ol>'

report_html += '''
    </div>
  </div>'''

# Replace old demo with full report
new_landing = landing.replace(old_demo, report_html)

with open("index.html", "w", encoding="utf-8") as f:
    f.write(new_landing)

print("✓ Landing page updated with full 8-section Batman report")
print(f"  Report sections: {len(report['sections'])}")
print(f"  Sources: {len(report['sources'])}")
print(f"  Report HTML inserted between demo box markers")
